### ISSUE TITLE
add posibility to change nationality

### ISSUE THREAD

**Issue by vgeck** [expertanalytics/cvcreator#3]
The nationality is set to norwegian, but some people are eg. born in danmark or germany, we need an optional input to be able to adapt to that fact.

**Comment by jonathf** [comment]
Indeed.

I've updated the code (and template) to add the field `Nationality` under the `Basic` section..

Note 1:
As a result of not having the field before, the section for nationality will be removed from the end document when updating the software without updating the local yaml as well.

Note 2:
This only affects the `default` template since the others do not use the nationality field.
